version: "3"

services:
  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb:latest-pg14
    restart: always
    environment:
      POSTGRES_USER: timescaledb
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/timescaledb:/var/lib/postgresql/data
      - ./seeders/init-timescaledb.sql:/docker-entrypoint-initdb.d/create_tables.sql
  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./seeders/init-postgres.sql:/docker-entrypoint-initdb.d/create_tables.sql
